# Generated by Django 5.0.1 on 2024-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='home_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('dep_head', 'Department Head'), ('dean', 'Dean'), ('admin', 'Admin')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='residential_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
