# Generated by Django 5.0.1 on 2024-02-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_courseregistration_department_and_more'),
        ('school_administration', '0010_alter_department_courses_alter_department_lecturers_and_more'),
        ('users', '0004_lecturer_level_student_level_student_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_level', to='school_administration.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_level', to='school_administration.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_dept', to='school_administration.department'),
        ),
    ]
