# Generated by Django 5.0.1 on 2024-02-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_departments'),
        ('users', '0005_alter_lecturer_level_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='lecturer', to='courses.course'),
        ),
    ]
