# Generated by Django 5.0.1 on 2024-02-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0014_department_program_duration_alter_faculty_dean'),
        ('users', '0007_customuser_nationality_customuser_religion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_dept', to='school_administration.department'),
        ),
    ]
