# Generated by Django 5.0.1 on 2024-02-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='level',
        ),
    ]
