version: '3.8'
services:
  postgres:
    container_name: schoolms-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER:  schoolms_user
      POSTGRES_PASSWORD: schoolms_password
      POSTGRES_DB: schooldb
      PGDATA: /data/fozy_data
    volumes:
      - ./fozy_data:/data/fozy_data
    ports:
      - 5432:5432
    networks:
      - schoolms-network
    restart: unless-stopped  
      
networks:
  schoolms-network:
   driver: bridge

