# Generated by Django 5.0.1 on 2024-02-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_initial'),
        ('school_administration', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='department',
            name='lecturers',
            field=models.ManyToManyField(to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(to='users.student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean', to='users.departmenthead'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='school_administration.faculty'),
        ),
        migrations.AddField(
            model_name='level',
            name='level_courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='level',
            name='level_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='school_administration.department'),
        ),
        migrations.AddField(
            model_name='level',
            name='students',
            field=models.ManyToManyField(to='users.student'),
        ),
    ]
