# Generated by Django 5.0.1 on 2024-02-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
