# Generated by Django 5.0.1 on 2024-02-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0002_initial'),
        ('users', '0002_rename_address_customuser_home_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='department',
            name='lecturers',
        ),
        migrations.RemoveField(
            model_name='department',
            name='students',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level_courses',
        ),
        migrations.RemoveField(
            model_name='level',
            name='students',
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_level', to='school_administration.level'),
        ),
        migrations.AddField(
            model_name='department',
            name='program_duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='staff_advisor_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_advisor_level', to='users.lecturer'),
        ),
    ]
