# Generated by Django 5.0.1 on 2024-02-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0003_alter_department_name_alter_department_short_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='courses',
        ),
    ]
