# Generated by Django 5.0.1 on 2024-02-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0004_remove_level_level_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='level',
        ),
    ]
