# Generated by Django 5.0.1 on 2024-02-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_session_courseregistration_semester_and_more'),
        ('school_administration', '0005_rename_name_level_level'),
        ('users', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.AddField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='department',
            name='lecturers',
            field=models.ManyToManyField(to='users.lecturer'),
        ),
        migrations.AddField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(to='users.student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='departments',
            field=models.ManyToManyField(to='school_administration.department'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.ManyToManyField(to='school_administration.level'),
        ),
    ]
