# Generated by Django 5.0.1 on 2024-02-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0006_remove_department_faculty_department_courses_and_more'),
        ('users', '0004_lecturer_level_student_level_student_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean', to='users.departmenthead'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='faculty', to='school_administration.department'),
        ),
    ]
