# Generated by Django 5.0.1 on 2024-02-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0007_alter_faculty_dean_alter_faculty_departments'),
        ('users', '0004_lecturer_level_student_level_student_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean', to='users.departmenthead'),
        ),
    ]
