# Generated by Django 5.0.1 on 2024-02-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_courseregistration_department_and_more'),
        ('school_administration', '0009_alter_faculty_dean'),
        ('users', '0004_lecturer_level_student_level_student_student_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='department', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='department',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='department', to='users.lecturer'),
        ),
        migrations.AlterField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='department', to='users.student'),
        ),
        migrations.AlterField(
            model_name='level',
            name='staff_advisor_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_advisor_level', to='users.lecturer'),
        ),
    ]
