# Generated by Django 5.0.1 on 2024-02-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0010_alter_department_courses_alter_department_lecturers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='program_duration',
        ),
    ]
