# Generated by Django 5.0.1 on 2024-02-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0011_remove_department_program_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='courses',
        ),
    ]
