# Generated by Django 5.0.1 on 2024-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0016_department_courses'),
    ]

    operations = [
        migrations.RemoveField(model_name='level',
            name='level',
            field=models.CharField(unique=True),),
    ]
