# Generated by Django 5.0.1 on 2024-02-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0017_alter_level_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
