# Generated by Django 5.0.1 on 2024-02-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_course_code_alter_course_course_credit_and_more'),
        ('school_administration', '0018_level_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='level', to='courses.course'),
        ),
    ]
