# Generated by Django 5.0.1 on 2024-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0019_level_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.IntegerField(),
        ),
    ]
