# Generated by Django 5.0.1 on 2024-02-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_administration', '0020_level_name_alter_level_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.ManyToManyField(blank=True, related_name='department', to='school_administration.level'),
        ),
    ]
