# Generated by Django 5.0.1 on 2024-02-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('school_administration', '0001_initial'),
        ('school_artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_courses', to='school_administration.department'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_administration.department'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_administration.level'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_artifacts.session'),
        ),
    ]
