# Generated by Django 5.0.1 on 2024-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_semester',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.BooleanField(default=True),
        ),
    ]
