# Generated by Django 5.0.1 on 2024-02-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_level_and_more'),
        ('school_administration', '0004_remove_department_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_administration.department'),
            preserve_default=False,
        ),
    ]
