# Generated by Django 5.0.1 on 2024-02-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_course_prerequisite_and_more'),
        ('school_administration', '0005_rename_name_level_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_level',
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_levels', to='school_administration.level'),
        ),
    ]
