# Generated by Django 5.0.1 on 2024-02-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_course_level_course_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_prerequisite',
        ),
    ]
