# Generated by Django 5.0.1 on 2024-02-07 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_course_prerequisite'),
        ('school_administration', '0005_rename_name_level_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_level', to='school_administration.level'),
        ),
    ]
