# Generated by Django 5.0.1 on 2024-02-08 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_session_courseregistration_semester_and_more'),
        ('school_administration', '0009_alter_faculty_dean'),
        ('school_artifacts', '0003_remove_semester_session_session_semesters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='department',
        ),
        migrations.AlterField(
            model_name='course',
            name='department_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='school_administration.department'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_artifacts.semester'),
        ),
    ]
