# Generated by Django 5.0.1 on 2024-02-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_courseregistration_department_and_more'),
        ('school_administration', '0012_remove_department_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department_course',
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='course', to='school_administration.department'),
        ),
    ]
