# Generated by Django 5.0.1 on 2024-02-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_department_course_course_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='departments',
        ),
    ]
