# Generated by Django 5.0.1 on 2024-02-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_departments_alter_course_course_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='departments',
        ),
    ]
