# Generated by Django 5.0.1 on 2024-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_unit',
            field=models.IntegerField(default=0),
        ),
    ]
