# Generated by Django 5.0.1 on 2024-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_courseregistration_unique_together_and_more'),
        ('school_artifacts', '0003_remove_semester_session_session_semesters'),
        ('users', '0009_rename_lecturer_dept_lecturer_lecturer_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('student', 'semester')},
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='courses.course'),
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
    ]
